'use strict';
const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

const SalesFlipkart = sequelize.define('SalesFlipkart', {
  id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true },
  brand_id: { type: DataTypes.UUID, allowNull: false },
  month: { type: DataTypes.INTEGER },
  year: { type: DataTypes.INTEGER },
  inventory_type: { type: DataTypes.STRING },
  filename: { type: DataTypes.STRING },
  created_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  date: { type: DataTypes.DATE },
  seller_gstin: { type: DataTypes.STRING },
  seller_state: { type: DataTypes.STRING },
  order_id: { type: DataTypes.STRING },
  order_item_id: { type: DataTypes.STRING },
  order_type: { type: DataTypes.STRING },
  event_type: { type: DataTypes.STRING },
  event_sub_type: { type: DataTypes.STRING },
  order_date: { type: DataTypes.DATE },
  order_approval_date: { type: DataTypes.DATE },
  sku: { type: DataTypes.STRING },
  fg: { type: DataTypes.STRING },
  fsn: { type: DataTypes.STRING },
  item_description: { type: DataTypes.STRING },
  hsn_code: { type: DataTypes.STRING },
  quantity: { type: DataTypes.INTEGER },
  fulfilment_type: { type: DataTypes.STRING },
  warehouse_id: { type: DataTypes.STRING },
  ship_from_state: { type: DataTypes.STRING },
  price_before_discount: { type: DataTypes.DECIMAL(15, 4) },
  total_discount: { type: DataTypes.DECIMAL(15, 4) },
  price_after_discount: { type: DataTypes.DECIMAL(15, 4) },
  shipping_charges: { type: DataTypes.DECIMAL(15, 4) },
  final_taxable_sales_value: { type: DataTypes.DECIMAL(15, 4) },
  final_shipping_taxable_value: { type: DataTypes.DECIMAL(15, 4) },
  final_invoice_amount: { type: DataTypes.DECIMAL(15, 4) },
  gst_rate: { type: DataTypes.DECIMAL(10, 4) },
  cgst_rate: { type: DataTypes.DECIMAL(10, 4) },
  sgst_rate: { type: DataTypes.DECIMAL(10, 4) },
  igst_rate: { type: DataTypes.DECIMAL(10, 4) },
  cgst_amount: { type: DataTypes.DECIMAL(15, 4) },
  sgst_amount: { type: DataTypes.DECIMAL(15, 4) },
  igst_amount: { type: DataTypes.DECIMAL(15, 4) },
  final_cgst_tax: { type: DataTypes.DECIMAL(15, 4) },
  final_sgst_tax: { type: DataTypes.DECIMAL(15, 4) },
  final_igst_tax: { type: DataTypes.DECIMAL(15, 4) },
  shipping_cgst_tax: { type: DataTypes.DECIMAL(15, 4) },
  shipping_sgst_tax: { type: DataTypes.DECIMAL(15, 4) },
  shipping_igst_tax: { type: DataTypes.DECIMAL(15, 4) },
  tcs_igst_amount: { type: DataTypes.DECIMAL(15, 4) },
  tcs_cgst_amount: { type: DataTypes.DECIMAL(15, 4) },
  tcs_sgst_amount: { type: DataTypes.DECIMAL(15, 4) },
  total_tcs: { type: DataTypes.DECIMAL(15, 4) },
  tds_rate: { type: DataTypes.DECIMAL(10, 4) },
  tds_amount: { type: DataTypes.DECIMAL(15, 4) },
  buyer_invoice_id: { type: DataTypes.STRING },
  buyer_invoice_date: { type: DataTypes.DATE },
  buyer_invoice_amount: { type: DataTypes.DECIMAL(15, 4) },
  final_invoice_number: { type: DataTypes.STRING },
  billing_state: { type: DataTypes.STRING },
  billing_pincode: { type: DataTypes.STRING },
  shipping_state: { type: DataTypes.STRING },
  shipping_pincode: { type: DataTypes.STRING },
  business_name: { type: DataTypes.STRING },
  business_gstin: { type: DataTypes.STRING },
  is_shopsy_order: { type: DataTypes.BOOLEAN },
  tally_ledger: { type: DataTypes.STRING },
  imei: { type: DataTypes.STRING },
}, { tableName: 'sales_flipkart', timestamps: true });

module.exports = SalesFlipkart;
