'use strict';
const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

const SalesJiomart = sequelize.define('SalesJiomart', {
  id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true },
  brand_id: { type: DataTypes.UUID, allowNull: false },
  month: { type: DataTypes.INTEGER },
  year: { type: DataTypes.INTEGER },
  filename: { type: DataTypes.STRING },
  created_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  seller_gstin: { type: DataTypes.STRING },
  order_id: { type: DataTypes.STRING },
  order_item_id: { type: DataTypes.STRING },
  order_type: { type: DataTypes.STRING },
  order_date: { type: DataTypes.DATE },
  order_approval_date: { type: DataTypes.DATE },
  type: { type: DataTypes.STRING },
  shipment_number: { type: DataTypes.STRING },
  original_shipment_number: { type: DataTypes.STRING },
  fulfillment_type: { type: DataTypes.STRING },
  fulfiller_name: { type: DataTypes.STRING },
  product_name: { type: DataTypes.STRING },
  product_id: { type: DataTypes.STRING },
  sku: { type: DataTypes.STRING },
  fg: { type: DataTypes.STRING },
  hsn_code: { type: DataTypes.STRING },
  order_status: { type: DataTypes.STRING },
  event_type: { type: DataTypes.STRING },
  event_sub_type: { type: DataTypes.STRING },
  quantity: { type: DataTypes.INTEGER },
  buyer_invoice_id: { type: DataTypes.STRING },
  original_invoice_id: { type: DataTypes.STRING },
  buyer_invoice_date: { type: DataTypes.DATE },
  tcs_date: { type: DataTypes.DATE },
  buyer_invoice_amount: { type: DataTypes.DECIMAL(15, 4) },
  shipped_from_state: { type: DataTypes.STRING },
  billed_from_state: { type: DataTypes.STRING },
  billing_pincode: { type: DataTypes.STRING },
  billing_state: { type: DataTypes.STRING },
  delivery_pincode: { type: DataTypes.STRING },
  delivery_state: { type: DataTypes.STRING },
  seller_coupon_code: { type: DataTypes.STRING },
  offer_price: { type: DataTypes.DECIMAL(15, 4) },
  seller_coupon_amount: { type: DataTypes.DECIMAL(15, 4) },
  final_invoice_amount: { type: DataTypes.DECIMAL(15, 4) },
  tax_type: { type: DataTypes.STRING },
  taxable_value: { type: DataTypes.DECIMAL(15, 4) },
  igst_rate: { type: DataTypes.DECIMAL(10, 4) },
  igst_amount: { type: DataTypes.DECIMAL(15, 4) },
  cgst_rate: { type: DataTypes.DECIMAL(10, 4) },
  cgst_amount: { type: DataTypes.DECIMAL(15, 4) },
  sgst_rate: { type: DataTypes.DECIMAL(10, 4) },
  sgst_amount: { type: DataTypes.DECIMAL(15, 4) },
  tcs_igst_rate: { type: DataTypes.DECIMAL(10, 4) },
  tcs_igst_amount: { type: DataTypes.DECIMAL(15, 4) },
  tcs_cgst_rate: { type: DataTypes.DECIMAL(10, 4) },
  tcs_cgst_amount: { type: DataTypes.DECIMAL(15, 4) },
  tcs_sgst_rate: { type: DataTypes.DECIMAL(10, 4) },
  tcs_sgst_amount: { type: DataTypes.DECIMAL(15, 4) },
  total_tcs_deducted: { type: DataTypes.DECIMAL(15, 4) },
  tds_rate: { type: DataTypes.DECIMAL(10, 4) },
  tds_amount: { type: DataTypes.DECIMAL(15, 4) },
  final_gst_rate: { type: DataTypes.DECIMAL(10, 4) },
}, { tableName: 'sales_jiomart', timestamps: true });

module.exports = SalesJiomart;
