'use strict';
const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

const SalesAmazon = sequelize.define('SalesAmazon', {
  id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true },
  brand_id: { type: DataTypes.UUID, allowNull: false },
  month: { type: DataTypes.INTEGER },
  year: { type: DataTypes.INTEGER },
  inventory_type: { type: DataTypes.STRING },
  file_type: { type: DataTypes.STRING },
  filename: { type: DataTypes.STRING },
  created_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  date: { type: DataTypes.DATE },
  seller_gstin: { type: DataTypes.STRING },
  invoice_number: { type: DataTypes.STRING },
  invoice_date: { type: DataTypes.DATE },
  transaction_type: { type: DataTypes.STRING },
  order_id: { type: DataTypes.STRING },
  shipment_id: { type: DataTypes.STRING },
  shipment_date: { type: DataTypes.DATE },
  order_date: { type: DataTypes.DATE },
  shipment_item_id: { type: DataTypes.STRING },
  quantity: { type: DataTypes.INTEGER },
  item_description: { type: DataTypes.STRING },
  asin: { type: DataTypes.STRING },
  hsn_sac: { type: DataTypes.STRING },
  sku: { type: DataTypes.STRING },
  fg: { type: DataTypes.STRING },
  product_tax_code: { type: DataTypes.STRING },
  bill_from_city: { type: DataTypes.STRING },
  bill_from_state: { type: DataTypes.STRING },
  bill_from_country: { type: DataTypes.STRING },
  bill_from_postal_code: { type: DataTypes.STRING },
  ship_from_city: { type: DataTypes.STRING },
  ship_from_state: { type: DataTypes.STRING },
  ship_from_country: { type: DataTypes.STRING },
  ship_from_postal_code: { type: DataTypes.STRING },
  ship_to_city: { type: DataTypes.STRING },
  ship_to_state: { type: DataTypes.STRING },
  ship_to_state_tally_ledger: { type: DataTypes.STRING },
  final_invoice_number: { type: DataTypes.STRING },
  ship_to_country: { type: DataTypes.STRING },
  ship_to_postal_code: { type: DataTypes.STRING },
  invoice_amount: { type: DataTypes.DECIMAL(15, 4) },
  tax_exclusive_gross: { type: DataTypes.DECIMAL(15, 4) },
  total_tax_amount: { type: DataTypes.DECIMAL(15, 4) },
  cgst_rate: { type: DataTypes.DECIMAL(10, 4) },
  sgst_rate: { type: DataTypes.DECIMAL(10, 4) },
  utgst_rate: { type: DataTypes.DECIMAL(10, 4) },
  igst_rate: { type: DataTypes.DECIMAL(10, 4) },
  compensatory_cess_rate: { type: DataTypes.DECIMAL(10, 4) },
  principal_amount: { type: DataTypes.DECIMAL(15, 4) },
  principal_amount_basis: { type: DataTypes.DECIMAL(15, 4) },
  cgst_tax: { type: DataTypes.DECIMAL(15, 4) },
  sgst_tax: { type: DataTypes.DECIMAL(15, 4) },
  utgst_tax: { type: DataTypes.DECIMAL(15, 4) },
  igst_tax: { type: DataTypes.DECIMAL(15, 4) },
  compensatory_cess_tax: { type: DataTypes.DECIMAL(15, 4) },
  final_tax_rate: { type: DataTypes.DECIMAL(10, 4) },
  final_taxable_sales_value: { type: DataTypes.DECIMAL(15, 4) },
  final_taxable_shipping_value: { type: DataTypes.DECIMAL(15, 4) },
  final_cgst_tax: { type: DataTypes.DECIMAL(15, 4) },
  final_sgst_tax: { type: DataTypes.DECIMAL(15, 4) },
  final_igst_tax: { type: DataTypes.DECIMAL(15, 4) },
  final_shipping_cgst_tax: { type: DataTypes.DECIMAL(15, 4) },
  final_shipping_sgst_tax: { type: DataTypes.DECIMAL(15, 4) },
  final_shipping_igst_tax: { type: DataTypes.DECIMAL(15, 4) },
  final_amount_receivable: { type: DataTypes.DECIMAL(15, 4) },
  shipping_amount: { type: DataTypes.DECIMAL(15, 4) },
  shipping_amount_basis: { type: DataTypes.DECIMAL(15, 4) },
  shipping_cgst_tax: { type: DataTypes.DECIMAL(15, 4) },
  shipping_sgst_tax: { type: DataTypes.DECIMAL(15, 4) },
  shipping_utgst_tax: { type: DataTypes.DECIMAL(15, 4) },
  shipping_igst_tax: { type: DataTypes.DECIMAL(15, 4) },
  shipping_cess_tax: { type: DataTypes.DECIMAL(15, 4) },
  gift_wrap_amount: { type: DataTypes.DECIMAL(15, 4) },
  gift_wrap_amount_basis: { type: DataTypes.DECIMAL(15, 4) },
  gift_wrap_cgst_tax: { type: DataTypes.DECIMAL(15, 4) },
  gift_wrap_sgst_tax: { type: DataTypes.DECIMAL(15, 4) },
  gift_wrap_utgst_tax: { type: DataTypes.DECIMAL(15, 4) },
  gift_wrap_igst_tax: { type: DataTypes.DECIMAL(15, 4) },
  gift_wrap_compensatory_cess_tax: { type: DataTypes.DECIMAL(15, 4) },
  item_promo_discount: { type: DataTypes.DECIMAL(15, 4) },
  item_promo_discount_basis: { type: DataTypes.DECIMAL(15, 4) },
  item_promo_tax: { type: DataTypes.DECIMAL(15, 4) },
  shipping_promo_discount: { type: DataTypes.DECIMAL(15, 4) },
  shipping_promo_discount_basis: { type: DataTypes.DECIMAL(15, 4) },
  shipping_promo_tax: { type: DataTypes.DECIMAL(15, 4) },
  gift_wrap_promo_discount: { type: DataTypes.DECIMAL(15, 4) },
  gift_wrap_promo_discount_basis: { type: DataTypes.DECIMAL(15, 4) },
  gift_wrap_promo_tax: { type: DataTypes.DECIMAL(15, 4) },
  tcs_cgst_rate: { type: DataTypes.DECIMAL(10, 4) },
  tcs_cgst_amount: { type: DataTypes.DECIMAL(15, 4) },
  tcs_sgst_rate: { type: DataTypes.DECIMAL(10, 4) },
  tcs_sgst_amount: { type: DataTypes.DECIMAL(15, 4) },
  tcs_utgst_rate: { type: DataTypes.DECIMAL(10, 4) },
  tcs_utgst_amount: { type: DataTypes.DECIMAL(15, 4) },
  tcs_igst_rate: { type: DataTypes.DECIMAL(10, 4) },
  tcs_igst_amount: { type: DataTypes.DECIMAL(15, 4) },
  warehouse_id: { type: DataTypes.STRING },
  fulfillment_channel: { type: DataTypes.STRING },
  payment_method_code: { type: DataTypes.STRING },
  bill_to_city: { type: DataTypes.STRING },
  bill_to_state: { type: DataTypes.STRING },
  bill_to_country: { type: DataTypes.STRING },
  bill_to_postal_code: { type: DataTypes.STRING },
  customer_bill_to_gstin: { type: DataTypes.STRING },
  customer_ship_to_gstin: { type: DataTypes.STRING },
  buyer_name: { type: DataTypes.STRING },
  credit_note_number: { type: DataTypes.STRING },
  credit_note_date: { type: DataTypes.DATE },
  irn_number: { type: DataTypes.STRING },
  irn_filing_status: { type: DataTypes.STRING },
  irn_date: { type: DataTypes.DATE },
  irn_error_code: { type: DataTypes.STRING },
}, { tableName: 'sales_amazon', timestamps: true });

module.exports = SalesAmazon;
