'use strict';
const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

const SalesNykaa = sequelize.define('SalesNykaa', {
  id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true },
  brand_id: { type: DataTypes.UUID, allowNull: false },
  month: { type: DataTypes.DECIMAL(10, 4) },
  filename: { type: DataTypes.STRING },
  created_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  period: { type: DataTypes.STRING },
  parent_vendor_code: { type: DataTypes.STRING },
  parent_vendor_name: { type: DataTypes.STRING },
  common_name: { type: DataTypes.STRING },
  other_name: { type: DataTypes.STRING },
  nykaa_orderno: { type: DataTypes.STRING },
  externorderno: { type: DataTypes.STRING },
  eretail_orderno: { type: DataTypes.STRING },
  product_sku: { type: DataTypes.STRING },
  product_name: { type: DataTypes.TEXT },
  brand: { type: DataTypes.STRING },
  hsn_code: { type: DataTypes.STRING },
  mrp_per_unit: { type: DataTypes.DECIMAL(15, 4) },
  dp_per_unit: { type: DataTypes.DECIMAL(15, 4) },
  sp_per_unit: { type: DataTypes.DECIMAL(15, 4) },
  dp_per_unit_brand: { type: DataTypes.DECIMAL(15, 4) },
  dp_nykaa_funded: { type: DataTypes.DECIMAL(15, 4) },
  dp_brand_funded: { type: DataTypes.DECIMAL(15, 4) },
  sp_coupon_nykaa_funded: { type: DataTypes.DECIMAL(15, 4) },
  sp_brand_funded: { type: DataTypes.DECIMAL(15, 4) },
  nsv_net_sale_value: { type: DataTypes.DECIMAL(15, 4) },
  taxable_amount: { type: DataTypes.DECIMAL(15, 4) },
  base_value: { type: DataTypes.DECIMAL(15, 4) },
  tax_amount: { type: DataTypes.DECIMAL(15, 4) },
  tax_percent: { type: DataTypes.DECIMAL(10, 4) },
  cgst: { type: DataTypes.DECIMAL(15, 4) },
  sgst: { type: DataTypes.DECIMAL(15, 4) },
  ugst: { type: DataTypes.DECIMAL(15, 4) },
  igst: { type: DataTypes.DECIMAL(15, 4) },
  order_shipping_city: { type: DataTypes.STRING },
  order_shipping_state: { type: DataTypes.STRING },
  order_type: { type: DataTypes.STRING },
  child_vendor_gst: { type: DataTypes.STRING },
  invoiceno: { type: DataTypes.STRING },
  tracking_no: { type: DataTypes.STRING },
  return_awb: { type: DataTypes.STRING },
  order_date: { type: DataTypes.DATE },
  ship_date: { type: DataTypes.DATE },
  delivery_date: { type: DataTypes.DATE },
  quantity: { type: DataTypes.DECIMAL(15, 4) },
  rule_name: { type: DataTypes.STRING },
  yes_or_no: { type: DataTypes.STRING },
  countif: { type: DataTypes.DECIMAL(15, 4) },
  tcs: { type: DataTypes.DECIMAL(15, 4) },
  final_status: { type: DataTypes.STRING },
  previous_final_status: { type: DataTypes.STRING },
}, { tableName: 'sales_nykaa', timestamps: true });

module.exports = SalesNykaa;
