'use strict';
const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

const SalesShopify = sequelize.define('SalesShopify', {
  id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true },
  brand_id: { type: DataTypes.UUID, allowNull: false },
  month: { type: DataTypes.INTEGER },
  year: { type: DataTypes.INTEGER },
  filename: { type: DataTypes.STRING },
  created_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  date: { type: DataTypes.DATE },
  day: { type: DataTypes.DATE },
  sales: { type: DataTypes.STRING },
  product_variant_sku: { type: DataTypes.STRING },
  fg: { type: DataTypes.STRING },
  product_variant_id: { type: DataTypes.STRING },
  product_variant_title: { type: DataTypes.STRING },
  shipping_region: { type: DataTypes.STRING },
  billing_region: { type: DataTypes.STRING },
  tally_ledger: { type: DataTypes.STRING },
  sales_ledger: { type: DataTypes.STRING },
  invoice_number: { type: DataTypes.STRING },
  customer_name: { type: DataTypes.STRING },
  order_fulfillment_status: { type: DataTypes.STRING },
  product_id: { type: DataTypes.STRING },
  product_title: { type: DataTypes.STRING },
  order_id: { type: DataTypes.STRING },
  billing_city: { type: DataTypes.STRING },
  shipping_city: { type: DataTypes.STRING },
  gross_sales: { type: DataTypes.DECIMAL(15, 4) },
  discounts: { type: DataTypes.DECIMAL(15, 4) },
  returns: { type: DataTypes.DECIMAL(15, 4) },
  net_sales: { type: DataTypes.DECIMAL(15, 4) },
  shipping_charges: { type: DataTypes.DECIMAL(15, 4) },
  return_fees: { type: DataTypes.DECIMAL(15, 4) },
  taxes: { type: DataTypes.DECIMAL(15, 4) },
  total_sales: { type: DataTypes.DECIMAL(15, 4) },
  quantity_returned: { type: DataTypes.INTEGER },
  quantity_ordered: { type: DataTypes.INTEGER },
  quantity_ordered_per_order: { type: DataTypes.INTEGER },
  final_qty: { type: DataTypes.INTEGER },
  gst_rate: { type: DataTypes.DECIMAL(10, 4) },
  taxable_value: { type: DataTypes.DECIMAL(15, 4) },
  igst: { type: DataTypes.DECIMAL(15, 4) },
  cgst: { type: DataTypes.DECIMAL(15, 4) },
  sgst: { type: DataTypes.DECIMAL(15, 4) },
}, { tableName: 'sales_shopify', timestamps: true });

module.exports = SalesShopify;
